### ISSUE TITLE
Connection Timeout after Lab Completion: Bot Loop

### ISSUE THREAD

**Issue by dee1337** [HughJeffner/FFRK-LabMem#122]
LabMem 6.4.0 is stuck in a loop, when a connection timeout happens directly after lab completion.

Screenshot: 
![image](https://user-images.githubusercontent.com/6726242/148367238-e50d5a66-3acc-4b8c-8489-27b453abd00f.png)

Not sure, if a connection timeout can be detected, but a specific handling would make the bot more stable and faster. Connection timeouts in general happen a lot these days, connecting from europe (connection from europe has ~30 hops to dena's ec2-us-west1 aws servers).

**Comment by HughJeffner** [comment]
Seems like the restart lab process is very sensitive to connection timeouts since it has so many requests.  If any one of them times out then the restart timer kicks in.

I'm looking into ways to detect a connection timeout but the proxy dependency I am using doesn't seem to have an event I can hook into.  I see a couple ways I could maybe pull this off, but none of them are pretty:

1. Start a timer for each request and disabling the timer on the corresponding response.  If a timer ever elapses, then check the screen pixels to see if the connection timed out dialog is present
2. Using a single timer, reset it each time a request is made through the proxy.  If the timer elapses, check if the bot is not in the battle state and then check the screen pixels to see if the connection timeout dialog is present

Checking for the on-screen dialog would basically be finding both a 'blue' and 'brown' button in the middle of the screen with the blue one above the brown one, then it would tap the blue button.

**Comment by slartifer** [comment]
I wonder if there's a more general issue with the logic for finding the Complete Dungeon dialog.  If I'm not mistaken, the Dungeon Complete dialog is never going to appear twice -- even if you reset FFRK while it's up the first time.  So it may not be a reliable indicator to look for, after a post-completion restart.

![image](https://user-images.githubusercontent.com/17887799/148685016-6fe08179-a438-4adf-a568-9eeb13ddccaa.png)

(The disable at the end, above, was manual, when I returned 6.5 hours after the failure -- but my device was sitting on the title screen (with the holiday tableau and the one button), not a place I've ever seen the bot get stuck previously.)

**Comment by HughJeffner** [comment]
Possibly, although it just checks for the presence of the complete dialog and continues on if it wasn't found (showing the yellow message in your screenshot).  Enabling debug messages for the Lab component should shed a bit of light on the issue.

More concerning is your screenshot, not sure how it got stuck in the restarted state, there's a default 3 minutes timer that should have timed out.

**Comment by slartifer** [comment]
After commenting, I turned on ADB logging and immediately got what appeared to be a backdated message from 02:14 that the ADB connection had died -- so maybe that would explain it.  Closing and reopening labmem resolved the issue (and cleared the message before I thought to screenshot it).

**Comment by HughJeffner** [comment]
I added basic timeout detection in 7.2.  It might not cover all cases yet but it's a start.
