### ISSUE TITLE
If ending run sequence due to stamina (with pots turned off), scheduled starts fail

### ISSUE THREAD

**Issue by slartifer** [HughJeffner/FFRK-LabMem#190]
...because, it looks like, the stamina restore window is never closed, and enabling lab fails from that window:

![image](https://user-images.githubusercontent.com/17887799/156761317-5ea7d003-9949-44e2-851c-0d8edd93c09b.png)

**Comment by HughJeffner** [comment]
Interesting find, and one I never encountered because I use the `Close and restart FFRK when starting` option

Would either that or the upcoming `Wait for stamina to recover` option be an acceptable work-around?  Looks like you are using multiple schedules that may or may not trigger while the bot is still running. The restart command is skipped if it's already running.

**Comment by slartifer** [comment]
That's right, it was just the first scheduled restart (at 3:05) that failed, due to the dialogue being open.  The others behaved as expected.

(The schedules I just use to kick labmem if it dies in the middle of the night for some reason that's fatal to the sequence, but which it can restart out of.  Hasn't happened in a long while.)

I think using the "close and restart" option would be an acceptable workaround, or "wait for stamina to recover" -- either one.

(In this case, I'd actually intended it not to restart -- I wanted to keep going for a bit, but avoid overgrinding magia on a few PCs -- but forgot about the scheduled restarts.  So this was an accidental discovery.)

**Comment by HughJeffner** [comment]
This is mostly resolved already with the various workarounds, but in 7.9 I made it navigate back to the main lab screen when out of stamina so it should support this workflow

**Comment by HughJeffner** [comment]
Resolved in #218
