### ISSUE TITLE
Get 'timed out waiting for fatigue' on the first battle of a lab run

### ISSUE THREAD

**Issue by HughJeffner** [HughJeffner/FFRK-LabMem#36]
This is due to the fatigue values getting downloaded (and stored locally on the client) when entering the lab.  So the client never requests them.

Subsequent battles work normally

**Comment by alextcl** [comment]
Short terms fix:
Set a flag after listening to enter labyrinth dungeon request, ignore the fatigue values if the flag present, then reset the flag. Safe to do this after the first battle since the party fatigues will always be downloaded.

Long and unproductive fix:
buddy_info and party_list only available at subsequent battle hence not able construct party map before the first battle. We can however capture the party selection request before entering dungeon.

**Comment by HughJeffner** [comment]
I opted for the first fix by listening for the enter lab request, updating the fatigue level for all units to 3 (with or without buddy id), and signaling the fatigue values have been downloaded.  I think this should work for 99.9% of cases.

The only problem I see is that if I don't have the buddy id's yet any fatigue-altering events before the first battle won't update the fatigue values.  This would only be a problem when entering a lab for the first time after enabling/starting the bot since on a restart the bot actually picks up the party info.

**Comment by HughJeffner** [comment]
This has been added in 6.5
