### ISSUE TITLE
Daily reset during lab restart causes "inventory full" message

### ISSUE THREAD

**Issue by HughJeffner** [HughJeffner/FFRK-LabMem#80]

**Comment by tsukih** [comment]
Hello ,
first of all thankk you for your work it's juste amazing and easy to use but since 2 days i face an issues inventory full .
![image](https://user-images.githubusercontent.com/96569841/147213929-3ec3f7a1-0400-4080-8274-342b17ccfb34.png)
as you can see in the screenshot i face this issues on 7h ( the lab was running since 22h on the day before )  so it's not near the daily reset 
and yesterday i face it after only one lab at 23h ( lab start around 21h) so again not a daily reset timing 
do you know if i can check something that can cause that ?
for information i'm am at 205/350 hero artifact so far before the limite .

thank you in advance for the answer and as i say at the beginning thank you for the job it's awesome

**Comment by HughJeffner** [comment]
If this happens again can you post a screenshot of the emulator?

I could immediately tell it was the daily reset in my case since "The date has changed" dialog message was visible

**Comment by tsukih** [comment]
yes sure i'll try to let some lab running this night i'll keep you update if i face or not the issues

**Comment by HughJeffner** [comment]
Well I found a [mistake](https://github.com/HughJeffner/FFRK-LabMem/blob/fb8b473957294247c824b7cd6e45621c66a51c4d/FFRK-LabMem/Machines/Lab.Actions.cs#L754) that causes it to give the "inventory full"message and disable if it doesn't find the "enter" button on this screen for 20 tries:

![Screenshot_2021-12-23-13-41-13](https://user-images.githubusercontent.com/9453825/147285644-19c250cb-350b-4af7-af6a-a997c03eaa96.png)

So starting with 6.4 it shouldn't disable, and would get picked up by the hang timer at least

**Comment by tsukih** [comment]
nice at the moment i test it for 5 hours and finish 2 lab whitout error ( currently on the third one)

**Comment by tsukih** [comment]
quick update : no issues on the last 3 day of test

**Comment by HughJeffner** [comment]
This should be fully fixed in the newest release

Give it a try and let me know if you have any more issues

**Comment by tsukih** [comment]
i'll try during the next day . i'll update you

**Comment by HughJeffner** [comment]
Gonna go ahead and close this one but please re-open it if the issue still persists
